version: '3'

services:
  api:
    build: .
    container_name: bank_api
    ports:
      - 3999:3001
    working_dir: /app
    volumes:
      - .:/app
    command: dev
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: bank_database
    restart: always
    ports:
      - 3998:3306
    env_file:
      - .env
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    cap_add:
      - SYS_NICE
